service: serverless-rest-api-with-dynamodb

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-northeast-1:*:*"
  stage: dev
  region: ap-northeast-1
#  apiKeys:
#    - share-images-key

functions:
  create:
    handler: shareImages.create
    events:
      - http:
          path: shareImages
          method: post
          cors: true
#          private: true

  list:
    handler: shareImages.list
    events:
      - http:
          path: shareImages
          method: get
          cors: true
#          private: true

  get:
    handler: shareImages.get
    events:
      - http:
          path: shareImages/{id}
          method: get
          cors: true
#          private: true

  update:
    handler: shareImages.update
    events:
      - http:
          path: shareImages/{id}
          method: put
          cors: true
#          private: true

  delete:
    handler: shareImages.delete
    events:
      - http:
          path: shareImages/{id}
          method: delete
          cors: true
#          private: true

resources:
  Resources:
    ShareImagesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: createdAt
            AttributeType: N
          -
            AttributeName: createdMonth
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
          -
            AttributeName: createdAt
            KeyType: RANGE
        GlobalSecondaryIndexes:
          -
            IndexName: globalIndex1
            KeySchema:
              -
                AttributeName: createdMonth
                KeyType: HASH
              -
                AttributeName: createdAt
                KeyType: RANGE
            Projection:
                ProjectionType: ALL
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'shareImages'
